export const TREASURE_ABI = [
  {
    type: "function",
    name: "nextId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getRound",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [
      { type: "address" },
      { type: "uint8" },
      { type: "uint8" },
      { type: "uint8" },
      { type: "bool" },
      { type: "bool" },
      { type: "uint64" },
      { type: "uint256" },
      { type: "uint256" },
      { type: "bytes32" },
    ],
  },
  {
    type: "function",
    name: "quotePayout",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "quoteVrfFee",
    stateMutability: "view",
    inputs: [{ type: "uint32" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "createRound",
    stateMutability: "payable",
    inputs: [{ type: "uint8" }, { type: "uint8" }, { type: "uint8" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "requestSeedFromTreasury",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256" }, { type: "uint32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "openTile",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256" }, { type: "uint8" }, { type: "uint8" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cashOut",
    stateMutability: "nonpayable",
    inputs: [{ type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "fund",
    stateMutability: "payable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [{ type: "address" }, { type: "uint256" }],
    outputs: [],
  },
  {
    type: "event",
    name: "RoundCreated",
    inputs: [
      { indexed: true, name: "id", type: "uint256" },
      { indexed: true, name: "player", type: "address" },
      { indexed: false, name: "rows", type: "uint8" },
      { indexed: false, name: "cols", type: "uint8" },
      { indexed: false, name: "bombs", type: "uint8" },
      { indexed: false, name: "stake", type: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SeedFulfilled",
    inputs: [
      { indexed: true, name: "id", type: "uint256" },
      { indexed: false, name: "requestId", type: "uint256" },
      { indexed: false, name: "seed", type: "bytes32" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TileRevealed",
    inputs: [
      { indexed: true, name: "id", type: "uint256" },
      { indexed: false, name: "idx", type: "uint256" },
      { indexed: false, name: "bomb", type: "bool" },
      { indexed: false, name: "safeReveals", type: "uint64" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CashedOut",
    inputs: [
      { indexed: true, name: "id", type: "uint256" },
      { indexed: true, name: "player", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    anonymous: false,
  },
] as const;
