[profile.default]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
src = "src"
test = "test"
libs = ["lib"]

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "randomness-solidity/=lib/randomness-solidity/"
]
